Repository yiisoft/arrays, pull requests merged in 2021-01, with the labels that each got.

#80 Add ArrayHelper::pathExists
  README.md
  src/ArrayHelper.php
  tests/ArrayHelper/ArrayHelperTest.php
  tests/ArrayHelper/KeyAndPathExistsTest.php
Labels: status:code review

#81 Enhanced PHPDocs for ArrayHelper::getValueByPath
  src/ArrayHelper.php
Labels: status:code review, type:docs

#83 Fix ArrayHelper::filter for filters with keys for non-array values + refactoring tests
  src/ArrayHelper.php
  tests/ArrayHelper/ArrayHelperTest.php
  tests/ArrayHelper/FilterTest.php
Labels: status:code review, type:bug

#82 Remove modifiers
  README.md
  src/ArrayHelper.php
  src/Modifier/InsertValueBeforeKey.php
  src/Modifier/ModifierInterface.php
  src/Modifier/RemoveKeys.php
  src/Modifier/ReplaceValue.php
  src/Modifier/ReverseBlockMerge.php
  src/Modifier/ReverseValues.php
  src/Modifier/UnsetValue.php
  tests/ArrayHelper/ApplyModifiersTest.php
  tests/ArrayHelper/MergeTest.php
Labels: status:code review

#85 Remove support use Closure with return multiple keys for ArrayHelper::multisort + Importve test multisort Closure + Improve phpdoc + Update dev dependencies
  composer.json
  src/ArrayAccessTrait.php
  src/ArrayHelper.php
  src/ArraySorter.php
  src/ArrayableInterface.php
  src/ArrayableTrait.php
  tests/ArraySorterTest.php
Labels: status:code review
